server {
    listen 443 ssl;
    server_name ft_trans.42.fr;

    # Caminho dos certificados gerados
    ssl_certificate /etc/nginx/ssl/transcendence.crt;
    ssl_certificate_key /etc/nginx/ssl/transcendence.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/frontend;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirecionamento para a API JAVA (Spring)
    location /api/java/ {
        proxy_pass http://api:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Redirecionamento para a API PYTHON (Django/FastAPI)
    location /api/python/ {
        proxy_pass http://python-service:8000/;
        proxy_set_header Host $host;
    }
}

# Redirecionar HTTP (80) para HTTPS (443)
server {
    listen 80;
    server_name ft_trans.42.fr;
    return 301 https://$host$request_uri;
}