spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    open-in-view: false

  mail:
    host: ${SPRING_MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${SPRING_MAIL_PORT:2525}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: false

server:
  port: 8080

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  refresh:
    token: ${GOOGLE_REFRESH_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
